# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'esparclientRN' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for esparclientRN

  #target 'esparclientRN-tvOSTests' do
  #  inherit! :search_paths
  #  # Pods for testing
  #end

  #target 'esparclientRNTests' do
  #  inherit! :search_paths
  #  # Pods for testing
  #end

end

#target 'esparclientRN-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for esparclientRN-tvOS

  #target 'esparclientRN-tvOSTests' do
  #  inherit! :search_paths
  #  # Pods for testing
  #end
#
#end
